In [1]:
!conda env list

'conda' is not recognized as an internal or external command,
operable program or batch file.

In [2]:
%load_ext autoreload

In [3]:

%autoreload 2
from tt_gutenberg.data import *

In [ ]:
from tt_gutenberg.authors import *
list_authors(by_languages=True, alias=True)

In [23]:
from tt_gutenberg.transform import get_data

get_data().head()

,gutenberg_author_id,author_x,alias,birthdate,deathdate,wikipedia,aliases,gutenberg_id,title,author_y,language_x,gutenberg_bookshelf,rights,has_text,language_y,total_languages
0,1,United States,U.S.A.,NaN,NaN,https://en.wikipedia.org/wiki/United_States,U.S.A.,2,The United States Bill of Rights\r\nThe Ten Or...,United States,en,Politics/American Revolutionary War/United Sta...,Public domain in the USA.,True,en,1
1,1,United States,U.S.A.,NaN,NaN,https://en.wikipedia.org/wiki/United_States,U.S.A.,5,The United States Constitution,United States,en,United States/Politics/American Revolutionary ...,Public domain in the USA.,True,en,1
2,1,United States,U.S.A.,NaN,NaN,https://en.wikipedia.org/wiki/United_States,U.S.A.,116,Motion Pictures of the Apollo 11 Lunar Landing,United States,en,Browsing: Computers & Technology/Browsing: Eng...,Public domain in the USA.,True,en,1
3,1,United States,U.S.A.,NaN,NaN,https://en.wikipedia.org/wiki/United_States,U.S.A.,239,Radar Map of the United States,United States,en,Browsing: Travel & Geography,Public domain in the USA.,True,en,1
4,1,United States,U.S.A.,NaN,NaN,https://en.wikipedia.org/wiki/United_States,U.S.A.,251,1995 United States Congressional Address Book,United States,en,Browsing: History - American/Browsing: Politics,Public domain in the USA.,True,en,1

In [5]:
from tt_gutenberg.data import load_authors
load_authors().head()

,gutenberg_author_id,author,alias,birthdate,deathdate,wikipedia,aliases
0,1,United States,U.S.A.,NaN,NaN,https://en.wikipedia.org/wiki/United_States,U.S.A.
1,3,"Lincoln, Abraham",NaN,1809.0,1865.0,https://en.wikipedia.org/wiki/Abraham_Lincoln,"United States President (1861-1865)/Lincoln, Abe"
2,4,"Henry, Patrick",NaN,1736.0,1799.0,https://en.wikipedia.org/wiki/Patrick_Henry,NaN
3,5,"Adam, Paul",NaN,1849.0,1931.0,https://de.wikipedia.org/wiki/Paul_Adam_(Buchb...,NaN
4,7,"Carroll, Lewis","Dodgson, Charles Lutwidge",1832.0,1898.0,https://en.wikipedia.org/wiki/Lewis_Carroll,"Dodgson, Charles Lutwidge"

In [6]:
from tt_gutenberg.data import  load_languages
languages = load_languages()
languages.head()

   gutenberg_id language  total_languages
0             1       en                1
1             2       en                1
2             3       en                1
3             4       en                1
4             5       en                1

In [7]:
from tt_gutenberg.data import load_metadata
metadata = load_metadata()
metadata.head()

,gutenberg_id,title,author,gutenberg_author_id,language,gutenberg_bookshelf,rights,has_text
0,1,The Declaration of Independence of the United ...,"Jefferson, Thomas",1638.0,en,Politics/American Revolutionary War/United Sta...,Public domain in the USA.,True
1,2,The United States Bill of Rights\r\nThe Ten Or...,United States,1.0,en,Politics/American Revolutionary War/United Sta...,Public domain in the USA.,True
2,3,John F. Kennedy's Inaugural Address,"Kennedy, John F. (John Fitzgerald)",1666.0,en,Browsing: History - American/Browsing: Politics,Public domain in the USA.,True
3,4,Lincoln's Gettysburg Address\r\nGiven November...,"Lincoln, Abraham",3.0,en,US Civil War/Browsing: History - American/Brow...,Public domain in the USA.,True
4,5,The United States Constitution,United States,1.0,en,United States/Politics/American Revolutionary ...,Public domain in the USA.,True

In [8]:
authors = load_authors()

In [9]:
book_authors = pd.merge(authors, metadata, on='gutenberg_author_id') 
book_authors.head()

,gutenberg_author_id,author_x,alias,birthdate,deathdate,wikipedia,aliases,gutenberg_id,title,author_y,language,gutenberg_bookshelf,rights,has_text
0,1,United States,U.S.A.,NaN,NaN,https://en.wikipedia.org/wiki/United_States,U.S.A.,2,The United States Bill of Rights\r\nThe Ten Or...,United States,en,Politics/American Revolutionary War/United Sta...,Public domain in the USA.,True
1,1,United States,U.S.A.,NaN,NaN,https://en.wikipedia.org/wiki/United_States,U.S.A.,5,The United States Constitution,United States,en,United States/Politics/American Revolutionary ...,Public domain in the USA.,True
2,1,United States,U.S.A.,NaN,NaN,https://en.wikipedia.org/wiki/United_States,U.S.A.,116,Motion Pictures of the Apollo 11 Lunar Landing,United States,en,Browsing: Computers & Technology/Browsing: Eng...,Public domain in the USA.,True
3,1,United States,U.S.A.,NaN,NaN,https://en.wikipedia.org/wiki/United_States,U.S.A.,239,Radar Map of the United States,United States,en,Browsing: Travel & Geography,Public domain in the USA.,True
4,1,United States,U.S.A.,NaN,NaN,https://en.wikipedia.org/wiki/United_States,U.S.A.,251,1995 United States Congressional Address Book,United States,en,Browsing: History - American/Browsing: Politics,Public domain in the USA.,True

In [10]:
full= pd.merge(book_authors, languages, on='gutenberg_id')  
full.head()

,gutenberg_author_id,author_x,alias,birthdate,deathdate,wikipedia,aliases,gutenberg_id,title,author_y,language_x,gutenberg_bookshelf,rights,has_text,language_y,total_languages
0,1,United States,U.S.A.,NaN,NaN,https://en.wikipedia.org/wiki/United_States,U.S.A.,2,The United States Bill of Rights\r\nThe Ten Or...,United States,en,Politics/American Revolutionary War/United Sta...,Public domain in the USA.,True,en,1
1,1,United States,U.S.A.,NaN,NaN,https://en.wikipedia.org/wiki/United_States,U.S.A.,5,The United States Constitution,United States,en,United States/Politics/American Revolutionary ...,Public domain in the USA.,True,en,1
2,1,United States,U.S.A.,NaN,NaN,https://en.wikipedia.org/wiki/United_States,U.S.A.,116,Motion Pictures of the Apollo 11 Lunar Landing,United States,en,Browsing: Computers & Technology/Browsing: Eng...,Public domain in the USA.,True,en,1
3,1,United States,U.S.A.,NaN,NaN,https://en.wikipedia.org/wiki/United_States,U.S.A.,239,Radar Map of the United States,United States,en,Browsing: Travel & Geography,Public domain in the USA.,True,en,1
4,1,United States,U.S.A.,NaN,NaN,https://en.wikipedia.org/wiki/United_States,U.S.A.,251,1995 United States Congressional Address Book,United States,en,Browsing: History - American/Browsing: Politics,Public domain in the USA.,True,en,1

In [11]:
grouped = full.groupby('alias')['alias'].size()
grouped

alias
A Bushman                      1
Aaberg, Jens Christian         1
Aaron, Samuel Francis          2
Abbe, E. (Ernst)               1
Abbey, C. J. (Charles John)    1
                              ..
高明                             1
黃宗羲                            1
黃檗                             1
黃起有                            1
齊治平                            1
Name: alias, Length: 8647, dtype: int64

In [12]:
ranked=grouped.sort_values(ascending=False)
ranked.head(10)

alias
Wells, Herbert George              124
Jacobs, William Wymark             114
Chaney, John Griffith              114
Stevenson, R. L. (Robert Louis)    114
Ballantyne, Robert Michael         101
De Maupassant, Guy                  91
Lang, Walter Andrew                 83
Πλάτων                              70
Wangemann, Eduard Carl Otto         69
Barbour, R. H. (Ralph Henry)        68
Name: alias, dtype: int64

In [13]:
lang_counts =full.groupby('alias')['language_y'].nunique()
lang_counts

alias
A Bushman                      1
Aaberg, Jens Christian         1
Aaron, Samuel Francis          1
Abbe, E. (Ernst)               1
Abbey, C. J. (Charles John)    1
                              ..
高明                             1
黃宗羲                            1
黃檗                             1
黃起有                            1
齊治平                            1
Name: language_y, Length: 8647, dtype: int64

In [14]:
ranked=lang_counts.sort_values(ascending=False)
ranked.head(10)

alias
Grimm, Wilhelm Carl                      9
Grimm, Jacob Ludwig Carl                 9
Andersen, Hans Christian                 8
Alighieri, Dante                         8
Stevenson, R. L. (Robert Louis)          8
Wilde, Oscar Fingal O'Flahertie Wills    8
Poe, Edgar Allen                         7
Όμηρος                                   7
Chaney, John Griffith                    6
De Maupassant, Guy                       6
Name: language_y, dtype: int64

In [15]:
alias_list=ranked.index.tolist()
alias_list[:5]

['Grimm, Wilhelm Carl',
 'Grimm, Jacob Ludwig Carl',
 'Andersen, Hans Christian',
 'Alighieri, Dante',
 'Stevenson, R. L. (Robert Louis)']

In [16]:
authors.columns

Index(['gutenberg_author_id', 'author', 'alias', 'birthdate', 'deathdate',
       'wikipedia', 'aliases'],
      dtype='str')

In [17]:
authors.shape

(26077, 7)

In [18]:
authors.info

<bound method DataFrame.info of        gutenberg_author_id                   author  \
0                        1            United States
1                        3         Lincoln, Abraham
2                        4           Henry, Patrick
3                        5               Adam, Paul
4                        7           Carroll, Lewis
...                    ...                      ...
26072                58311  Wilmot-Buxton, Helen A.
26073                58312               Wood, Emma
26074                58314              Innes, Kate
26075                58315            Werner, M. R.
26076                58316           Nijland, G. J.

                           alias  birthdate  deathdate  \
0                         U.S.A.        NaN        NaN
1                            NaN     1809.0     1865.0
2                            NaN     1736.0     1799.0
3                            NaN     1849.0     1931.0
4      Dodgson, Charles Lutwidge     1832.0     1898.0
...                          ...        ...        ...
26072                        NaN        NaN        NaN
26073                        NaN        NaN        NaN
26074                        NaN        NaN        NaN
26075                        NaN        NaN        NaN
26076                        NaN        NaN        NaN

                                               wikipedia  \
0            https://en.wikipedia.org/wiki/United_States
1          https://en.wikipedia.org/wiki/Abraham_Lincoln
2            https://en.wikipedia.org/wiki/Patrick_Henry
3      https://de.wikipedia.org/wiki/Paul_Adam_(Buchb...
4            https://en.wikipedia.org/wiki/Lewis_Carroll
...                                                  ...
26072                                                NaN
26073                                                NaN
26074                                                NaN
26075                                                NaN
26076                                                NaN

                                                aliases
0                                                U.S.A.
1      United States President (1861-1865)/Lincoln, Abe
2                                                   NaN
3                                                   NaN
4                             Dodgson, Charles Lutwidge
...                                                 ...
26072                                               NaN
26073                                               NaN
26074                                               NaN
26075                                               NaN
26076                                               NaN

[26077 rows x 7 columns]>

In [19]:
authors['alias'].isna().sum()/len(authors)

np.float64(0.668251716071634)

In [20]:
authors['alias'].dropna().head(20)

0                                  U.S.A.
4               Dodgson, Charles Lutwidge
6                       Melville, Hermann
9                           Smith, Joseph
11    United States President (1809-1817)
12                         Jay, J. (John)
13                   Longfellow, Henry W.
16                 Townsend, George Tyler
25                  Wells, Herbert George
28                       Crayon, Geoffrey
29        Stevenson, R. L. (Robert Louis)
37                        Descartes, Rene
40                      Engels, Frederick
47        Thoreau, Henry D. (Henry David)
48                        Smith, Johnston
51                         Presno, Odd de
56                  Hawkins, Anthony Hope
67                      Tenniel, Sir John
69                                    EFF
72                    Lang, Walter Andrew
Name: alias, dtype: str

In [21]:
authors['alias'].value_counts()

alias
Jarvis, E. K.                3
Holmes, Gordon               2
Willis, R. (Robert)          2
U.S.A.                       1
Dodgson, Charles Lutwidge    1
                            ..
Moore, Dennis Times          1
Lee, Ernest Markham          1
Schulz, Christoph            1
Heald, Hazel Drake           1
Ball, Clifford Nankivell     1
Name: count, Length: 8647, dtype: int64